"""FakeAnalysisProvider — 테스트 전용 AI provider.

네트워크 호출 없음. 외부 API key 불필요.
동일한 prompt에 대해 항상 동일한 결과를 반환한다 (deterministic).

토큰 수 추정:
  prompt_tokens   ≈ len(prompt.split())  (whitespace 기준 단어 수)
  completion_tokens ≈ len(content.split())
  total_tokens    = prompt_tokens + completion_tokens

latency_ms: 고정값 42ms (테스트에서 값이 존재하는지만 확인)
"""
from __future__ import annotations

import hashlib

from app.services.ai_analysis.base import AnalysisProvider
from app.services.ai_analysis.schemas import AnalysisProviderResult

_FAKE_MODEL = "fake-1.0"
_FAKE_LATENCY_MS = 42

# prompt 내용에 관계없이 생성되는 구조화된 분석 템플릿.
# {prompt_hash}: prompt의 MD5 앞 8자리 (동일 prompt → 동일 응답 보장)
_RESPONSE_TEMPLATE = """\
## Summary
This is a deterministic fake analysis response for testing purposes.
Prompt fingerprint: {prompt_hash}

## Signal Quality
No real signal quality assessment performed. Fake provider active.

## Horizon Analysis
Fake horizon data only. No actual market analysis was conducted.

## BUY vs SELL
Fake result: BUY and SELL signals were not actually evaluated.

## Risks / Data Limitations
This response is generated by FakeAnalysisProvider and contains no real insights.
Do not use this output for any decision-making purpose.

## Improvement Ideas
1. Replace FakeAnalysisProvider with a real provider.
2. Configure OPENAI_API_KEY or ANTHROPIC_API_KEY.
3. Use get_analysis_provider("openai") or get_analysis_provider("anthropic").

## Next Experiments
N/A — fake provider active.
"""


def _prompt_hash(prompt: str) -> str:
    return hashlib.md5(prompt.encode(), usedforsecurity=False).hexdigest()[:8]


def _estimate_tokens(text: str) -> int:
    return max(1, len(text.split()))


class FakeAnalysisProvider(AnalysisProvider):
    """네트워크 호출 없이 deterministic 응답을 반환하는 테스트용 provider.

    동일한 prompt는 항상 동일한 content를 반환한다 (prompt_hash 포함).
    외부 의존성 없음 — 단위/통합 테스트 모두에서 안전하게 사용 가능.
    """

    async def analyze(
        self,
        prompt: str,
        *,
        model: str | None = None,
        timeout_seconds: int | None = None,
    ) -> AnalysisProviderResult:
        used_model = model or self.default_model()
        content = _RESPONSE_TEMPLATE.format(prompt_hash=_prompt_hash(prompt))
        prompt_tokens = _estimate_tokens(prompt)
        completion_tokens = _estimate_tokens(content)
        total_tokens = prompt_tokens + completion_tokens

        return AnalysisProviderResult(
            provider=self.provider_name(),
            model=used_model,
            content=content,
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            total_tokens=total_tokens,
            latency_ms=_FAKE_LATENCY_MS,
            finish_reason="stop",
            raw={
                "provider": self.provider_name(),
                "model": used_model,
                "prompt_hash": _prompt_hash(prompt),
                "fake": True,
            },
        )

    def provider_name(self) -> str:
        return "fake"

    def default_model(self) -> str:
        return _FAKE_MODEL
