"""add positions and position_events tables

Revision ID: 24d2fb48da11
Revises: 7ae9b0ab4419
Create Date: 2026-06-11 12:14:01.468233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24d2fb48da11'
down_revision: Union[str, Sequence[str], None] = '7ae9b0ab4419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol_code', sa.String(length=20), nullable=False),
    sa.Column('symbol_name', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'symbol_code', name='uq_positions_account_symbol')
    )
    op.create_table('position_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('buy_fill', 'sell_fill', 'sync', 'adjustment', name='position_event_type'), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('realized_pnl_delta', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('before_quantity', sa.Integer(), nullable=False),
    sa.Column('after_quantity', sa.Integer(), nullable=False),
    sa.Column('before_avg_entry_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('after_avg_entry_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'trades',
        sa.Column('position_applied_quantity', sa.Integer(), nullable=False, server_default='0'),
    )
    op.alter_column('trades', 'position_applied_quantity', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'position_applied_quantity')
    op.drop_table('position_events')
    op.drop_table('positions')
    # ### end Alembic commands ###
