"""add scheduler_runs table and signal_logs trade attempt tracking

Revision ID: 3b3a4a5434e4
Revises: 24d2fb48da11
Create Date: 2026-06-11 13:05:30.574776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b3a4a5434e4'
down_revision: Union[str, Sequence[str], None] = '24d2fb48da11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', 'skipped', name='scheduler_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduler_runs_job_id_started_at', 'scheduler_runs', ['job_id', 'started_at'], unique=False)

    trade_attempt_status = sa.Enum(
        'not_attempted', 'approved', 'rejected', 'error', name='trade_attempt_status'
    )
    trade_attempt_status.create(op.get_bind(), checkfirst=True)

    op.add_column('signal_logs', sa.Column('trade_id', sa.Integer(), nullable=True))
    op.add_column('signal_logs', sa.Column('trade_attempted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        'signal_logs',
        sa.Column(
            'trade_attempt_status',
            trade_attempt_status,
            nullable=False,
            server_default='not_attempted',
        ),
    )
    op.alter_column('signal_logs', 'trade_attempt_status', server_default=None)
    op.create_foreign_key(
        'fk_signal_logs_trade_id_trades', 'signal_logs', 'trades', ['trade_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_signal_logs_trade_id_trades', 'signal_logs', type_='foreignkey')
    op.drop_column('signal_logs', 'trade_attempt_status')
    op.drop_column('signal_logs', 'trade_attempted_at')
    op.drop_column('signal_logs', 'trade_id')
    op.drop_index('ix_scheduler_runs_job_id_started_at', table_name='scheduler_runs')
    op.drop_table('scheduler_runs')

    sa.Enum(name='trade_attempt_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
