"""add candle_ts to signal_logs

Revision ID: 7ae9b0ab4419
Revises: 858b17d91bf7
Create Date: 2026-06-10 21:44:15.369303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae9b0ab4419'
down_revision: Union[str, Sequence[str], None] = '858b17d91bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signal_logs', sa.Column('candle_ts', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_signal_logs_dedup', 'signal_logs', ['strategy_version_id', 'symbol_code', 'signal_type', 'candle_ts'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_signal_logs_dedup', 'signal_logs', type_='unique')
    op.drop_column('signal_logs', 'candle_ts')
    # ### end Alembic commands ###
