"""add signal_logs table

Revision ID: 858b17d91bf7
Revises: a7f291d981e6
Create Date: 2026-06-10 21:28:45.968200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '858b17d91bf7'
down_revision: Union[str, Sequence[str], None] = 'a7f291d981e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_code', sa.String(length=20), nullable=False),
    sa.Column('strategy_version_id', sa.Integer(), nullable=True),
    sa.Column('signal_type', sa.Enum('buy', 'sell', name='signal_type'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('short_ma', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('long_ma', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signal_logs_symbol_generated_at', 'signal_logs', ['symbol_code', 'generated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signal_logs_symbol_generated_at', table_name='signal_logs')
    op.drop_table('signal_logs')
    # ### end Alembic commands ###
