"""add core domain tables

Revision ID: a7f291d981e6
Revises: 
Create Date: 2026-06-10 20:28:25.499866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7f291d981e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.Enum('paper', 'live', name='account_type'), nullable=False),
    sa.Column('broker_account_no', sa.String(length=20), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_data',
    sa.Column('symbol_code', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('symbol_code', 'timeframe', 'ts')
    )
    op.create_index('ix_market_data_symbol_timeframe_ts', 'market_data', ['symbol_code', 'timeframe', 'ts'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('max_daily_loss_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('max_position_size', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('max_open_positions', sa.Integer(), nullable=False),
    sa.Column('max_trades_per_day', sa.Integer(), nullable=False),
    sa.Column('consecutive_loss_limit', sa.Integer(), nullable=False),
    sa.Column('emergency_stop', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('strategy_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_profit', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('avg_loss', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('mdd', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.Enum('draft', 'testing', 'active', 'retired', name='strategy_version_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'version_no', name='uq_strategy_version')
    )
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('strategy_version_id', sa.Integer(), nullable=True),
    sa.Column('signal_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', sa.Enum('approved', 'rejected', name='risk_event_result'), nullable=False),
    sa.Column('rule_name', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('strategy_version_id', sa.Integer(), nullable=True),
    sa.Column('symbol_code', sa.String(length=20), nullable=False),
    sa.Column('symbol_name', sa.String(length=100), nullable=True),
    sa.Column('side', sa.Enum('buy', 'sell', name='trade_side'), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('pnl_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('entry_reason', sa.Text(), nullable=True),
    sa.Column('exit_reason', sa.Text(), nullable=True),
    sa.Column('market_condition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_analysis_id', sa.Integer(), nullable=True),
    sa.Column('order_status', sa.Enum('pending', 'filled', 'partial', 'cancelled', 'rejected', name='order_status'), nullable=False),
    sa.Column('broker_order_id', sa.String(length=50), nullable=True),
    sa.Column('partial_fill', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('commission', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('tax', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('slippage', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('risk_events')
    op.drop_table('strategy_versions')
    op.drop_table('risk_configs')
    op.drop_table('strategies')
    op.drop_index('ix_market_data_symbol_timeframe_ts', table_name='market_data')
    op.drop_table('market_data')
    op.drop_table('accounts')
    # ### end Alembic commands ###
