"""add cost fields to position_events

Revision ID: e91c53ebe8e4
Revises: 3b3a4a5434e4
Create Date: 2026-06-12 11:43:52.316736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91c53ebe8e4'
down_revision: Union[str, Sequence[str], None] = '3b3a4a5434e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position_events', sa.Column('realized_pnl_delta_net', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('position_events', sa.Column('commission', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('position_events', sa.Column('tax', sa.Numeric(precision=18, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position_events', 'tax')
    op.drop_column('position_events', 'commission')
    op.drop_column('position_events', 'realized_pnl_delta_net')
    # ### end Alembic commands ###
